echo ....脚本by一串蓝色的数字....
echo ....正在换源......
sed -i 's@^\(deb.*stable main\)$@#\1\ndeb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24 stable main@' $PREFIX/etc/apt/sources.list
sed -i 's@^\(deb.*games stable\)$@#\1\ndeb https://mirrors.tuna.tsinghua.edu.cn/termux/game-packages-24 games stable@' $PREFIX/etc/apt/sources.list.d/game.list
sed -i 's@^\(deb.*science stable\)$@#\1\ndeb https://mirrors.tuna.tsinghua.edu.cn/termux/science-packages-24 science stable@' $PREFIX/etc/apt/sources.list.d/science.list
echo .......正在更新,期间进度一直不动按回车即可...
apt update && apt upgrade -y
echo ........安装nodejs........
apt install nodejs -y
echo ......nodejs切换为淘宝源.......
npm config set registry https://registry.npm.taobao.org
echo ......正在安装依赖.......
npm install got -g
npm install tough-cookie -g
npm install crypto-js -g
echo .......完成....


